### ISSUE TITLE
Japanese translation

### ISSUE THREAD

**Issue by 53able** [thedaviddias/Front-End-Performance-Checklist#100]
Hi, 
 Can I help with the Japanese translation?

https://github.com/GameWith/Front-End-Performance-Checklist

- [x] Introduction
- [x] HTML
- [x] CSS
- [x] Fonts
- [x] Images
- [x] JavaScript
- [x] Server (in progress)
- [x] JS Frameworks (in progress)

@thedaviddias

**Comment by nouvelle** [comment]
I also want to help translate into Japanese

@53able  @thedaviddias _

**Comment by 53able** [comment]
@nouvelle 
作業の粒度ですが、各セクションでPRを出して頂くと良いと思います🙏
また、着手する前にこちらへご報告していただくと、コンフリクトせずに済むので良いです👍

**Comment by 53able** [comment]
5. JavaScript からはじめます🙋‍♂️

**Comment by nouvelle** [comment]
@53able  
了解です！まずは先頭～2. CSS を翻訳担当します。
PRはセクションごとに出すようにしますね😉

**Comment by 53able** [comment]
@nouvelle

後出しになってしまいましたが、
日本語への翻訳スタイルは、[vuejs/jp.vuejs.org](https://jp.vuejs.org/) のものに準拠すると、非常に統一されて洗練されると思うのですが、どうでしょうか?
こちらは、Nuxt.jsでも採用されています。

> [Vue.js 公式サイト日本語翻訳ガイド](https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/CONTRIBUTING.md#%E7%BF%BB%E8%A8%B3%E3%82%B9%E3%82%BF%E3%82%A4%E3%83%AB)

**Comment by nouvelle** [comment]
@53able
ご提案ありがとうございます！
いいですね、それでいきましょう👍

**Comment by noguchi-hiroshi** [comment]
@53able 

Fonts: https://github.com/GameWith/Front-End-Performance-Checklist#fonts を着手します

**Comment by inosy22** [comment]
@53able 

> 6. Server (in progress)

こちら着手します！

**Comment by 53able** [comment]
@nouvelle マージの権限を付与しました。
![スクリーンショット 2020-02-21 12 52 12](https://user-images.githubusercontent.com/1005683/75003419-ff24d980-54aa-11ea-8daa-9c9e33155ff9.png)


PRのタイトルですが、みなさん統一にしたいと思います。
以下の提案でいかがでしょうか?

```
Translate: {{ Table of Contentsの名称 }}

例) Translate: Introduction, HTML
```

## マージの手順
1. PRのレビューが終わったら、最後に @53able  が `approved` にします。
2. 各自が `Squash and merge` ボタンを押してマージ実行してください。
コミット履歴に翻訳者の貢献した履歴が残ります😉

**Comment by nouvelle** [comment]
@53able

**4. Images**  
着手します！

**Comment by noguchi-hiroshi** [comment]
font 日曜日までには PR あげます...!

**Comment by 53able** [comment]
チェック項目の日本語訳は、 `ですます` 調ではなく、可能な限り名詞止めとするのが自然だと判断します。
後ほどまとめて、スタイルを統一しましょう。

@inosy22 @nouvelle @noguchi-hiroshi

**Comment by 53able** [comment]
日ごろよく使う言葉で、漢字ではなくひらがなで書くと読みやすいドキュメントになるかと思いしました。
次の記事が参考になりましたので共有します。

> https://hajimeteweb.jp/column/web_writing/special2.php

**Comment by 53able** [comment]
@noguchi-hiroshi @nouvelle @inosy22 
全体を通して翻訳のゆらぎを調整させていただきます。
