### ISSUE TITLE
Question: do you take reference updates?

### ISSUE THREAD

**Issue by jennifert** [thedaviddias/Front-End-Performance-Checklist#133]
Hello,

The references section mentions: 
` * 📖 [Front-End Performance Checklist 2018 [PDF, Apple Pages]](https://www.smashingmagazine.com/2018/01/front-end-performance-checklist-2018-pdf-pages/)`

This reference is updated yearly, with the latest link being: https://www.smashingmagazine.com/2021/01/front-end-performance-2021-free-pdf-checklist/

I did not want to open a pull request if it was a reference cite or anything like that.

Thanks.

**Comment by thedaviddias** [comment]
Hi @jennifert, you can open a PR to update the link, no problem! Thanks!

**Comment by jennifert** [comment]
Thank you for letting me contribute :)
