### ISSUE TITLE
Flag Vietnamese (translate) not correct

### ISSUE THREAD

**Issue by tronghieu60s** [thedaviddias/Front-End-Performance-Checklist#141]
In the Vietnamese translation, this icon is not the national flag of Vietnam 🇻🇮. I think it's the flag of the Virgin Islands.
This is the correct Vietnam flag: 🇻🇳
An image correct Vietnam flag: https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Vietnam.svg/1200px-Flag_of_Vietnam.svg.png

**Comment by thedaviddias** [comment]
Thanks @tronghieu60s for flagging this issue, could you open a PR for that?

**Comment by tronghieu60s** [comment]
I opened a PR.
