### ISSUE TITLE
Pingdom Uptime product for TTFB monitoring

### ISSUE THREAD

**Issue by pra85** [thedaviddias/Front-End-Performance-Checklist#16]
Even though Pingdom Uptime monitoring tool is not built for this but it does keep a record of all historical TTFB timings (Refer to screenshot). Should we include it in TTFB tooling section or would that confuse people?

![Image of Pingom Uptime Monitoring dashboard](https://i.imgur.com/wToJa5w.png)

**Comment by thedaviddias** [comment]
Hi @pra85, I think we can keep it just inside the top section of the Checklist. Usually, you'll find a lot of similar information on all the tools listed.

**Comment by pra85** [comment]
Yes, that would be a good choice to prevent confusion. We can add these tools (Pingdom Uptime monitoring and Uptime Robot) in the General Performance Tools section of the checklist ( https://github.com/thedaviddias/Front-End-Performance-Checklist#performance-tools )

**Comment by pra85** [comment]
Changes integrated into checklist via #17
