### ISSUE TITLE
Inline/async <script> should be placed BEFORE <link rel="stylesheet">.

### ISSUE THREAD

**Issue by dtinth** [thedaviddias/Front-End-Performance-Checklist#18]
According to the talk [FaCSSt—CSS and Performance @ 39:35](https://youtu.be/2Rn8an74khk?t=39m35s) about loading CSS and JS,

Example from the talk:

```html
<link rel="stylesheet" href="…">
<script>
  var script = document.createElement('script')
  script.src = '…'
  document.getElementByTagNames('head')[0].appendChild(script)
</script>
```

Since a `<script>` may alter the CSSOM of the previous `<link>` tag, the browser will not execute the `<script>` tag until all stylesheets declared beforehand finished loading.

**Comment by thedaviddias** [comment]
That's indeed something I forgot to mention. Do you propose a PR?

**Comment by thedaviddias** [comment]
Hey @dtinth, are you proposing a change or a new rule?

**Comment by dtinth** [comment]
In this case, I think it would be a new rule: Put analytics tracking script before `<link rel="stylesheet">`.

**Comment by yairEO** [comment]
@dtinth - This is true to any script which requires a download and not just "analytics tracking script", so a more general rule would be preferred
