### ISSUE TITLE
Above the fold content (including HTML markup, Images, CSS, JS) should be less than 70KB

### ISSUE THREAD

**Issue by pra85** [thedaviddias/Front-End-Performance-Checklist#26]
Google recommends that the above the fold content (including  HTML markup, Images, CSS, JS) should not weight more than 14.6KB (compressed) because of the first TCP packet size limit. Refer to these resources -

- https://developers.google.com/speed/docs/insights/PrioritizeVisibleContent
- https://books.google.com/books?id=FOYPDQAAQBAJ&pg=PT297&dq=14.6kB+html+size+performance

Should we add this information in the checklist?

**Comment by thedaviddias** [comment]
And think we could mention it, maybe not as a rule but like an annotation or add it to an existing rule. I feel hard to measure and hard to have for today's website. What do you think?

**Comment by pra85** [comment]
Indeed this is a bit difficult to achieve in a real-world use case. 

Should we reference the Google Insights resource ( https://developers.google.com/speed/docs/insights/PrioritizeVisibleContent ) in the Critical CSS section as that deals with the Above the Fold region?

**Comment by thedaviddias** [comment]
Yes, we should add the link as a link resource. I let you propose a PR if you want 😉
