### ISSUE TITLE
Lazy loading only for offscreen images

### ISSUE THREAD

**Issue by verlok** [thedaviddias/Front-End-Performance-Checklist#31]
Hi, 

thank you for creating the list I’ve always wanted to create and for mentioning my LazyLoad script. 

it’s very important to mention that LazyLoad should be used only for images that are offscreen, and the first N above the fold images should be loaded normally. 

This allows browsers to fetch the first images as soon as possible, way before JavaScript is downloaded, parsed and executed, and optimize performance.

**Comment by verlok** [comment]
You can read more best practices on how to load images on a repo I’ve recently created. 

https://github.com/verlok/productListingPageBestPractices/blob/master/README.md

What do you think?

**Comment by thedaviddias** [comment]
You're welcome @verlok and thank you so much for the work! I totally agree with you, it's indeed not specified but should be in the Checklist. Do you want to do a PR?

Thanks to point that out!

**Comment by verlok** [comment]
Sure! Will do. I just wanted to know what you think about that before doing that.

**Comment by thedaviddias** [comment]
Hi @verlok, I was reviewing your previous message and I was wondering why on mouseover and not on scrolling?

**Comment by verlok** [comment]
In most e-commerce websites e.g. yoox.com and others there is an alternative shot shown at mouseover, showing the cloth weared by a model. 

My point is: don’t load those alternative images at page landing, but load them lazily when the user requests them, mouseover-ing the product. 

If you take a look at [this repo](https://github.com/verlok/productListingPageBestPractices/) and the related live demo, it will all be clear.

**Comment by verlok** [comment]
Ssup?

**Comment by Brunomaio** [comment]
And now we got native lazy loading (sorry if it's already in the checklist / mentioned anywhere
https://addyosmani.com/blog/lazy-loading/

**Comment by verlok** [comment]
@Brunomaio it’s not a thing yet. 

They will come with Chrome 75 and only under a flag. 

Anyway, my vanilla-lazyload script already supports them, you can use LazyLoad to do native lazyloading where supported, and JavaScript lazyloading where not supported. 

Read this for more information:
https://www.andreaverlicchi.eu/native-lazy-loading-with-vanilla-lazyload/
