### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by fernandofawkes** [thedaviddias/Front-End-Performance-Checklist#5]
Hi,

i'd like to submit a translation for this.
What would be the best way of doing so? i created branch on my forked repo however i've seen translations added to a specific folder at the master branch on similar projects...

What would suit this project's case better?

**Comment by thedaviddias** [comment]
Hi @fernandofawkes! You can fork the project and do the translation on your forked version that stays on your github account. Like the [Front-End Checklist](https://github.com/thedaviddias/Front-End-Checklist#translations), we will add a link on the README.

That works for you?

**Comment by fernandofawkes** [comment]
Great!
this is my translation repo:
https://github.com/fernandofawkes/Front-End-Performance-Checklist

Thanks.

**Comment by thedaviddias** [comment]
Obrigado Fernando, começar por uma tradução em Português, tá ótimo!
