### ISSUE TITLE
frontendchecklist.io custom checklists

### ISSUE THREAD

**Issue by yunusga** [thedaviddias/Front-End-Performance-Checklist#52]
It would be nice to add functionality of custom check lists based on the main list of checks.

**Comment by thedaviddias** [comment]
Thanks @yunusga for the suggestion. It's actually something I was thinking to do as I'm building frontendchecklist.io entirely. It's why I'm not updating a lot the repo.

I'm working on allowing people to use a checklist within a team and be able to easily create a custom checklist based on the current existing checklist.

What do you think?

**Comment by yunusga** [comment]
Custom checklist for teams it's a good idea 👍
