### ISSUE TITLE
"Avoid having your website using HTTPS and serve files coming from source using HTTP." is not good perf advice

### ISSUE THREAD

**Issue by jj09** [thedaviddias/Front-End-Performance-Checklist#71]
Checklist recommend using HTTP2, but also recommend to not use HTTPS. However HTTP2 works only over TLS: https://caniuse.com/#search=http2 Thus HTTPS2 is recommended way: https://www.troyhunt.com/i-wanna-go-fast-https-massive-speed-advantage/

**Comment by thedaviddias** [comment]
Hey @jj09, like I mentioned on Twitter, I didn't express myself correctly, it should be something like "avoid having HTTP requests when your website is served by HTTPS".
