### ISSUE TITLE
Remove closing slash on void tags

### ISSUE THREAD

**Issue by carlotrimarchi** [thedaviddias/Front-End-Performance-Checklist#74]
Since in html5 the closing slash on void tags, such as in:

`<img src="my-image.jpg" alt="cat picture"/>`

is not mandatory, wouldn't it be better to remove it from the examples and actually add it as a low priority reccomendation in the same way it's reccomended to remove unnecessary attributes?

**Comment by thedaviddias** [comment]
You're right yes. Do you think better to amend the "unnecessary attributes" rule or create a new one?

**Comment by carlotrimarchi** [comment]
To me a separate rule would be clearer. Even though both rules deal with unnecessary stuff, their scope is different

**Comment by thedaviddias** [comment]
Agree, do you want to suggest a PR?
