### ISSUE TITLE
update project description

### ISSUE THREAD

**Issue by BO41** [thedaviddias/Front-End-Performance-Checklist#76]
currently the project description says
>The only Front-End Performance Checklist that runs faster than the others https://frontendchecklist.io(soon on)

But https://frontendchecklist.io/ is already online, so "soon on" should be removed :)

**Comment by thedaviddias** [comment]
The Front-End PERFORMANCE Checklist is not on the frontendchecklist.io... But soon, all checklist will be on just one single domain so...

**Comment by BO41** [comment]
okay, I thought the domain wasn't online at all.
