### ISSUE TITLE
APIs

### ISSUE THREAD

**Issue by arjunmenon** [thedaviddias/Front-End-Performance-Checklist#9]
Hey
Would be important also to know about APIs. If consuming, how to connect to them or if serving, how to deliver them?
Any real world language would almost always have to deal with APIs. That itself contributes to the point ["TOO many HTTP requests"](https://github.com/thedaviddias/Front-End-Performance-Checklist#server)

In Server, we can also talk about important performance enhancive techiniques like caching - page and db, load balancers, etc.

Would be also nice to know of ways to do it yourself, for eg, instead of saying pay to CDN which can get costly overtime, how can we do it on your own if starting with a small project, like having a different subdomains(cookie-free) to serve static content.

**Comment by thedaviddias** [comment]
Hi @arjunmenon, you are pointing out interesting subjects indeed. I didn't want to go to deep with the server side because it's still a "Front-End" Checklist and I just wanted to have enough elements that a normal Front-End could handle it. (but don't hesitate to add more content to the repo and we could review later).

Instead of paying for a CDN, I generally use Cloudflare (free version). That's the free CDN I know... (and I need to add the link in the checklist)

**Comment by SabinDiwan** [comment]
Wwoooo .congrats.i think while solving frew steping liike let me count 👣×real lost.just check how much i stayed on line.

**Comment by SabinDiwan** [comment]
Answered 100 questions.cried out!lol!blessed!smiled!gosh and PROUD!!!!MY DAUGHTER IS JUST GOT 311 BADGES .NOTEBOOKS.BOOK MAARKS.SELF DESIGNED
.NOW GETTING HER VISITING CARD AS WILL BE GETTING A TRADEMARK OFCOURSE AS WE HAVE SOME WHO IS EXTREMELY POWER WHO IS STUCK IN CHINA WHO NEEDS WHAT.3000 DOLLARS WHILE SHE ATTTENDED POLICE STATION ON 26TH WHILE U HAVE HER ID PASSPORT PICK PLANNING ATRIP?
AND IM STILL EXPLAINING THERE IS NOT ONE SINGLE PAPER OR CALL TO MY GUARDIAN WHO WILL THAN ACCEPT THAT IM NOT CRAZY?

**Comment by SabinDiwan** [comment]
Lol.ok how tto send a picture.god whr
.let me check.wat language so far u guys have l.eAR.NED .SORRY.SCIENCE SAYS SARCAISM  WORKS!!!COME ON.HERE A CERTIFIED FOOL S TALKING TO YOU.IMAGINE.U R PAYING ATTENTION TO WHO?

**Comment by SabinDiwan** [comment]
Say what?

**Comment by lcj3391105** [comment]
我想赠送礼物给你，可以吗？请回复邮件：451195959@163.com
